### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'ncov-tutorial/example-data.yaml'

### ISSUE THREAD

**Issue by kiranpatil222** [nextstrain/ncov#1108]
I tried to run the test dtata set nextrain build for ncov
i installed nextstrain and tried with zika data it worked

Expected to run as shown in the ncov Workflow but gave above error

**How to reproduce**
Steps to reproduce the current behavior:
1. Open / run ...
2.
3.

**Possible solution**
(optional)

**Your environment: if browsing Nextstrain online**
 - Operating system:
 - Browser:

**Your environment: if running Nextstrain locally**
Linux Ubuntu 18

**Additional context**

**Comment by joverlee521** [comment]
Hi @kiranpatil222, 

Did you run into this error while following the [Run using example data](https://docs.nextstrain.org/projects/ncov/en/latest/tutorial/example-data.html) tutorial? Please make sure to follow the [Setup](https://docs.nextstrain.org/projects/ncov/en/latest/tutorial/example-data.html#setup) steps to download the tutorial repository so that the workflow will have access to the `ncov-tutorial/example-data.yaml` file.

**Comment by kiranpatil222** [comment]
Hi Jover,

I was supposed to clone twice, one **ncov** for workflow and other for **ncov tutorial**, now i got it all fine. thanks
