### ISSUE TITLE
[Question] How does Nextstrain handle recombinant SARS-CoV-2 lineages in phylogenetic analysis?

### ISSUE THREAD

**Issue by llk578496** [nextstrain/ncov#1112]
Dear @genehack @tomkinsc @tsibley @huddlej @rvosa ,

Hello! We would like to perform a phylogenetic analysis including both XBB* genomes and non-XBB genomes. As recombination can violate the central assumptions of traditional phylogenetic analysis, we want to ensure that the analysis methodology used can appropriately handle these recombinant genomes.

We have searched through the [SARS-CoV-2 Workflow documentation](https://docs.nextstrain.org/projects/ncov/en/v13/), but it does not seem to directly address how Nextstrain handles recombinant genomes when reconstructing the phylogenetic tree.

We would greatly appreciate it if you could provide some guidance on the Nextstrain approach to accounting for recombination events in the SARS-CoV-2 phylogenetic analysis. This information would be very helpful for ensuring the reliability and accuracy of our analysis.

Thank you very much for your assistance! We look forward to hearing back from you.

Best regards,
Eddie

**Comment by huddlej** [comment]
Hi @llk578496, the short answer is that we typically don't account for recombination in our workflows. For example, [the Nextstrain workflow for SARS-CoV-2](https://github.com/nextstrain/ncov/blob/master/workflow/snakemake_rules/main_workflow.smk) runs a reference-based sequence alignment and builds a standard phylogeny from that alignment without any consideration of recombinant groups. Since we annotate each sequence in the analysis with Nextclade Pango lineages, we can identify recombinant groups in the tree based on those lineage annotations.

In our work with influenza where reassortment is common, our general approach has been to identify groups of sequences that most likely belong to the same reassortment group (i.e., have a shared history across all gene segments), build separate trees for each group, and then stitch the trees together into a single final tree for export to an Auspice JSON. You can find [one such example workflow from the Seattle Flu Study](https://github.com/seattleflu/augur-build/blob/master/Snakefile). Another recent example of this approach is [our workflow for whole-genome analysis of the H5N1 outbreak in cattle](https://github.com/nextstrain/avian-flu/blob/master/Snakefile.genome) where we select only the sequences we know to belong to the same monophyletic group across gene segments and build a tree from that subset. This latter workflow is a simpler version of the more complex pattern in the Seattle Flu Study workflow.

For SARS-CoV-2 analyses, you might reasonably be able to follow a similar pattern by grouping sequences with the same Pango lineage, aligning these, building a tree from them, and then merging all of the subtrees into a single tree for visualization in Auspice. As far as I know, we don't provide any tools yet to help with this merging of subtrees, but the Seattle Flu Study workflow linked above includes several custom scripts that could help you with this process.

I hope this helps a little!

**Comment by llk578496** [comment]
Hi @huddlej ,

Thanks a lot for your explanation! 

Best regards,
Eddie
