### ISSUE TITLE
Entropy calculation

### ISSUE THREAD

**Issue by rabiakasikci** [nextstrain/ncov#1124]
I downloaded the entropy results from Nexstrain and the sequences with GISAID IDs used for these results. However, I noticed that there are unknown parts in the sequences. How were the entropy calculations made with these unknown parts? Also, I could not find the code used for entropy calculation. Can you help me to understand this issue in more detail?

**Comment by jameshadfield** [comment]
Hi @rabiakasikci, for general background on the entropy panel see related posts at discussion.nextstrain.org, e.g. [How to interpret the entropy data](https://discussion.nextstrain.org/t/how-to-interpret-the-entropy-data/1138) and [How Shannon entropy calculated per codon?](https://discussion.nextstrain.org/t/how-shannon-entropy-calculated-per-codon/488).

> How were the entropy calculations made with these unknown parts? 

[Invalid bases / AAs](https://github.com/nextstrain/auspice/blob/835fbb23d61549da81fde3725b031ad8a24c74cf/src/util/entropy.js#L317-L322) don't contribute to the entropy (or counts, if you're looking at the counts instead of entropy).

> I could not find the code used for entropy calculation

Code is [here](https://github.com/nextstrain/auspice/blob/835fbb23d61549da81fde3725b031ad8a24c74cf/src/util/entropy.js#L45-L134). 

Let me know if you need more information!
