### ISSUE TITLE
There should be a branch site-rep_es

### ISSUE THREAD

**Issue by CristianPumaES6** [nextstrain/ncov#13]
Los branch actuales:

master
https
sit-esp_fr
sit-esp_pt

**Comment by jameshadfield** [comment]
Hi @CristianPumaES6  -- the spanish translation is complete for the 2020-01-25 sit rep (see https://github.com/nextstrain/ncov/blob/master/narratives/ncov_sit-rep_es_2020-01-25.md or https://nextstrain.org/narratives/ncov/sit-rep/es/2020-01-25) which is why there is no `sit-rep_es` branch. (But if you have proposed modifications please let us know via an issue or PR!)

When we have a new sit-rep, we will create a `sit-rep_es` branch (or similar) for the translation work 👍
