### ISSUE TITLE
Translate "How to interpret phylogenetic trees" to Italian

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#182]
We’d like to translate [“How to interpret phylogenetic trees”](https://nextstrain.org/narratives/trees-background) into Italian. This narrative is referenced in the latest hCov-19 report, and we hope it will help make that one and future situation reports more accessible. The file to translate is `ncov_trees-background_it.md` in branch `background_it` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/background_it/narratives/ncov_trees-background_it.md

After pushing your changes to GitHub, you can preview the translation here: https://nextstrain.org/community/narratives/nextstrain/ncov@background_it/trees-background/it/

Please add your name in parentheses to the end of the author list, so we can credit your work!

Since this narrative explains something more technical, it would be great if the phylogenetics experts can keep their eyes especially on this translation :)

If more than one of you are working on the document at a time feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to work. The French translation group has found this especially helpful, whatever works best for you.

As always, THANK YOU! It’s an honor to work with you all.

@aliceLedda @al-epo @whispererindarkness @enkelejdamiho

**Comment by al-epo** [comment]
@cassiawag , @whispererindarkness , @aliceLedda , 
I can start after I finish to translate  the main report. At a first look the specific language doesn’t  seem too difficult to me, but I am not an expert  in phylogenitic (I am a biophysicist  with some knowledge  in molecular biology ) so if someone  can supervise  me it would  be great. 

Thank you!

**Comment by aliceLedda** [comment]
Sorry, I think I have the accents now, so I am starting the translation.

**Comment by aliceLedda** [comment]
I am working on this right now...
Alice

**Comment by al-epo** [comment]
@aliceLedda  
What can I do? 
maybe I can start from the bottom of the document?

**Comment by aliceLedda** [comment]
Can you please do the end of the document where there are the credits etc
and leave the rest?
I need some one hourish beak right now and I think I'll need some 1 hour
and half later to finish this.
If you could come back in 3 hours and do the following it would be amazing.
Just first reread the italian without looking at the english and spot the
sentences that do not make much sense for you, then signal them and or
correct them. Sometimes I am not being strictly literal, but I am aiming at
conveying the real meaning of the english sentence.
For example phylogeny I have never heard it used in Italian, although I
haven't spoken about this much in Italian. I prefer to translate it as
albero filogenetico
Other problem is genetic divergence, which in English has a meaning
somewhat general and in Italian means more fixed mutation and divergence as
a result of evolution. Since this is not the case here I prefer to
translate it with distanza genetica (anyway I will write a more general
email about this because it might be a nuance that we would like to take
into account even in English).
Another word that I question is sample (verb) as campionamento. I know it
is a translation in Italian, but it might not convey the message of what we
are doing here. In my view this is more used for inanimate things, like
soil, ice, sea water. Here I would rather use raccolta dei campioni, which
is more used for blood and urine samples.
Finally, please refrain from using the word significativo if whatever is
significativo is not explicitly backed by statistics (in english
significant).
I will keep adding to this list of technical words if I find more instances.
I am sorry to be so boring, normally I would be more open to licenze
poetiche!
Great work everybody!! I am very impressed!!!
Alice

**Comment by al-epo** [comment]
Ciao Alice, 
- I just finished the end of documents with the credits
- I agree with you that some of the words in English do not traslate directly to Italian, we have to find some sort of "best approximation" 
- I will come back in around 3 hours and read the italian as you suggest.

**Comment by aliceLedda** [comment]
Thanks so much!!
It is very valuable to be able to test my translation on you before giving
it to the public.
We need to be sure to give the exact message the narrative wants to give.
A presto!
Alice

**Comment by al-epo** [comment]
@aliceLedda  I am starting to read and comment you last version

**Comment by aliceLedda** [comment]
Unfortunately I haven't finished yet, but your comments are more than
welcome!!
There is an awful definition of functional mutation that I need to fix...
Thanks!!

**Comment by al-epo** [comment]
@aliceLedda 
I corrected small typos and accents
I commented with <!-- AL :  proposing a different translation two sentences that I found a bit difficult  to understand in italian. It is challenging translating technical scientific English in Italian!

**Comment by aliceLedda** [comment]
thanks, I'll go through it!!
That's exactly what I needed!
Alice

**Comment by aliceLedda** [comment]
Ragazzi,
I've done all of the scientific part.
Can anyone check if it does make sense in Italian and point me to the
awkward sentences?
I'll be back in an hour or so!
(otherwise I will just reread it myself)
Thanks everyone!
Alice

**Comment by al-epo** [comment]
ok!

**Comment by al-epo** [comment]
@aliceLedda  
I corrected few typos, you left in english the titles of the last two paragraphs, I put them in English in the comments <!-- AL : 
Also I am not sure about the traslation of infer with inferire. I suggest dedurre 
or  in this case infer is used as "inferenza statistica" ? 
Overall  is very clear!

**Comment by aliceLedda** [comment]
Esatto, I meant in the sense of inferenza statistica or in this case
inferenza dal modello...
Yes I forgot to change the two headers.
And I think I missed one of your notes previously because I accepted just
one of them...
Thank you for the comments, they were very helpful!
Anyway I will reread it in half an hour.
Thanks again!

Alice

**Comment by sarameiqi** [comment]
@cassiawag did you add me to this branch too? If not, could you do it?
Thanks!

**Comment by whispererindarkness** [comment]
Hi all, I made a few minor technical update to the translation, fixing HTML tags and translating a couple of subtitle. Let me know if you need further help.

**Comment by aliceLedda** [comment]
@al-epo <https://github.com/al-epo> I did not get what you meant with this
note. Anyway I don't especially like my translation in that point and the
meaning is clear, so go on and change it if you feel like!

I accepted all your comments except the ones about inferred.
Dear everyone,
my part is done, if you want to have a look, correct typos or signal
sentences that do not feel right, please feel free to do.
I am  going to bed and will be able to read emails in some seven hours.
For the US people, if nobody says anything and you want to publish it
before you go to bed, I think it's fine!

Wow! I am impressed by this collaborative work!
Great job everyone!
Goodnight!

Alice

**Comment by al-epo** [comment]
@aliceLedda  I meant to change " questo significa " in " significa". I made the change now. 
Good night !
Alessia

**Comment by aliceLedda** [comment]
Sorry Alessia, I am too sleepy... Thanks for changing it!!

Perfect then!
Huston (but it's actually Seattle, is it?) we're done here! You can publish
it!
Perfectly on time, as promised!

Goodnight!
Alice

**Comment by sarameiqi** [comment]
I spotted a couple of issues that need fixing. Let me know when you add me so that I can upload the changes. Thank you all for your amazing work!! It is lovely to work with you all!

**Comment by cassiawag** [comment]
Hi @sarameiqi, you should have access to push to branches in the `ncov` repo. Let me know if this is not working for you. Thanks for your eyes on this.

**Comment by sarameiqi** [comment]
> Esatto, I meant in the sense of inferenza statistica or in this case inferenza dal modello... Yes I forgot to change the two headers. And I think I missed one of your notes previously because I accepted just one of them... Thank you for the comments, they were very helpful! Anyway I will reread it in half an hour. Thanks again! Alice
> […](#)
> On Sun, Mar 15, 2020, 21:12 al-epo ***@***.***> wrote: @aliceLedda <https://github.com/aliceLedda> I corrected few typos, you left in english the titles of the last two paragraphs, I put them in English in the comments  sono state inferite statisticamente.
It sounds clearer from my point of view as not-expert on the topic. Inferite all alone sounds really strange. Let me know if it's ok!

**Comment by aliceLedda** [comment]
Ok, if you think it's clearer it's fine with me...
Alice

**Comment by al-epo** [comment]
@sarameiqi  and @aliceLedda  "inferite statisticamente" sounds  better to me!

Well done, great work!
It has been a pleasure work with you, 
Have a good day and stay safe !

Alessia

**Comment by sarameiqi** [comment]
I'm done with the proofreading, it's a really great way to expand my (little) knowledge on genomics and SARS-CoV-2.
Thank you all for this amazing job!

**Comment by aliceLedda** [comment]
Well then, can we consider it done and call @cassia to publish it?

**Comment by sarameiqi** [comment]
Ok for me, I added the translators' names.

**Comment by cassiawag** [comment]
You all are fast; well done! This is now live at: https://nextstrain.org/narratives/trees-background/it
I've updated the latest Italian narrative with the appropriate link: https://nextstrain.org/narratives/ncov/sit-rep/it/2020-03-13

Thanks!
