### ISSUE TITLE
Translate "How to interpret phylogenetic trees" into Korean

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#183]
We’d like to translate [“How to interpret phylogenetic trees”](https://nextstrain.org/narratives/trees-background) into Korean. This narrative is referenced in the latest hCov-19 report, and we hope it will help make that one and future situation reports more accessible. The file to translate is `ncov_trees-background_ko.md` in branch `background_ko` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/background_ko/narratives/ncov_trees-background_ko.md

After pushing your changes to GitHub, you can preview the translation here: https://nextstrain.org/community/narratives/nextstrain/ncov@background_ko/trees-background/ko/

Please add your name in parentheses to the end of the author list, so we can credit your work!

Since this narrative explains something more technical, it would be great if the phylogenetics experts can keep their eyes especially on this translation :)

If more than one of you are working on the document at a time feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to work. The French translation group has found this especially helpful, whatever works best for you.

As always, THANK YOU! It’s an honor to work with you all.

@hanbin973 @minkyuxyz @Bolloknoon @KyobinKang

**Comment by taehoonh** [comment]
Taehoon Ha

**Comment by taehoonh** [comment]
Taehoon Ha

**Comment by KyobinKang** [comment]
@cassiawag Hi, @taehoonh wants to contribute this but he told me that he does not have the write access; could you solve this problem? Thanks.

**Comment by cassiawag** [comment]
@taehoonh -- you should now have access. Thank you to both for your hard work on this!

**Comment by taehoonh** [comment]
@KyobinKang @cassiawag 
My pleasure. Now it works well. Thank you both.

**Comment by KyobinKang** [comment]
@cassiawag I've done with the document. After @taehoonh confirm it, this could be published. I tried to give a loose translation, instead of a word-for-word manner. Because this document is a guideline for readers who are not familiar with phylogenetic trees, so I focused on making it to be read easily.

@cassiawag I have a question. Among "An Example" part of the section "How should I interpret traits (colors) on the tree?", there is a sentence: "In the last example, we have only one sequence from orange, which could lead us to think that there was one introduction from orange into blue." Here, I think 'orange into blue' should be revised to 'blue into orange', based on the figure. Would you check on this?

@taehoonh Thanks for your heavy works! However I found that you removed some hyperlinks among the text, so I've revived all of the hyperlinks. Please leave them as they are if you would contribute to further documents. :)

**Comment by taehoonh** [comment]
@KyobinKang  Thank you for the correction. Please let me know if you need anything.

**Comment by cassiawag** [comment]
Thank you so much to you both!! If possible, I would love one more set of eyes on this b/c it's a background document that we will use for a long time. @minkyuxyz or @hanbin973, any chance you're available to review.

Hi @KyobinKang, good catch! Please adjust the tree accordingly.

**Comment by minkyuxyz** [comment]
I'll try to review it in a day or two. Thanks!

**Comment by taehoonh** [comment]
@minkyuxyz Thanks. I appreciate that.

**Comment by minkyuxyz** [comment]
Just finished the revision. Thank you for your contribution. They are very well translated. 

Following are the updates I made:
-Fixed minor grammars & typos
-Replaced all tokens of "계통도" and "계통유전학적 나무" by "계통수"
-Replaced all tokens of "샘플링" and "샘플 채취" by "표본 채집"
-Made honorifics consistent.

It's ready to go. @hanbin973 can review once more, if necessary. But I think it's generally publishable already.

**Comment by cassiawag** [comment]
Alright, I'll publish then. Thanks everyone for the good work!

**Comment by cassiawag** [comment]
It's live: https://nextstrain.org/narratives/trees-background/ko I've also update the links in the last situation report. Thanks all for an excellent job!
