### ISSUE TITLE
include reverse-complemented sequences

### ISSUE THREAD

**Issue by tolot27** [nextstrain/ncov#252]
Currently, the sequence from "Peru/010/2020" is excluded because it is reverse-complemented. Is this really necessary? The alignment program mafft has a parameter `--adjustdirection` which adjusts input sequences automatically and based on the first sequence (reference). Maybe, this can be implemented in the agur align step.

**Comment by tolot27** [comment]
Reverse-complemented sequences will be prefixed with `_R_` and hence can be recognised right after the alignment step. In case it is necessary for downstream analyses, the input file (`results/filtered.fasta` as far as I know) can be adjusted accordingly.

**Comment by tsibley** [comment]
Hi @tolot27, thanks for the suggestion!

We had some internal discussion about this back when that sequence was added. Agreed it would be great if `augur align` used mafft's `--adjustdirection`. As you note though, Augur will have to adjust the sequence name in the alignment output after mafft is done in order for subsequent steps to work, and we haven't had a chance to implement this in Augur yet.

Since our nCoV rebuilds are automated (but still get substantial manual review and adjustment before deployment), we need the RC support in `augur align` before including this Peru sequence to keep the rebuild process smooth and updating regularly. Excluding the sequence until Augur has that support was the easiest path forward.

Would you be willing to add this feature to Augur?

**Comment by tolot27** [comment]
> Would you be willing to add this feature to Augur?

Yes, I'll do. Maybe, I can commit a draft PR today.

**Comment by tsibley** [comment]
> Yes, I'll do. Maybe, I can commit a draft PR today.

Awesome, thank you!

**Comment by tolot27** [comment]
A draft is at https://github.com/imb-fmg/augur/commit/5c960a061a1373237eb1e8fe52417f74af8fe78c. I'll add a test case, update the docs and create a PR, tomorrow.

**Comment by Cholokiwi** [comment]
Hi @tolot27 and all, 
Would this feature be available for the analyses this week? It’d be great to see how these sequences from Peru fit in the tree. Reported cases so thave been linked to return travel from Spain and the UK.
Thanks,
Roy

**Comment by tolot27** [comment]
The feature is implemented. Hence, the issue is resolved.
