### ISSUE TITLE
Avoid excluding sequences that are not of technical error

### ISSUE THREAD

**Issue by melop** [nextstrain/ncov#279]
Currently, multiple sequences are excluded due to idiosyncratic reasons that are not thoroughly explained. 
While understandably identical haplotypes can be collapsed to decrease computational time, and sequences with problems of a technical nature (sequencing/assembly errors) can be excluded, subjective exclusion of samples may result in a distorted picture for the phylogeny of the species.
I strongly recommend defining a fixed set of rules for filtering sequences that can be universally applied to all sequences in the database.
It is difficult to understand, for instance, why "too divergent" or "confusing phylogeography" can be used as a reason for exclusion. These samples can be flagged after tree building, but no justification can be made to remove them a priori.

**Comment by emmahodcroft** [comment]
Hi @melop, thanks for your thoughts. Currently we exclude sequences when they have excess (or a lack of) diversity that indicates sequencing/assembly/alignment problems, and for other reasons including that the metadata doesn't line up with what we observe, dates seem incorrect, they cause errors in our pipeline, or sometimes because submitter have asked us not to put the data on Nextstrain yet, while they make corrections or so they can announce the data first (all data is still available on GISAID).

We have a lot of experience in managing this kind of analysis and these kinds of builds, so while I understand the lack of detailed explanation can be frustrating, please know we include every sequence that we feel is appropriate for the build. We take great care to do our best in ensuring the analyses we display is as scientifically sound as possible. 

If you'd like to see what the builds look like with these sequences, or see why a sequence was excluded, you are welcome to run the pipeline yourself and remove sequences from the `exclude.txt` file. This is the beauty of such an open-source pipeline - you can make your own version if you might disagree with our choices, or want to explore different options!

Best wishes, and keep well!

**Comment by melop** [comment]
Thanks! Sure, we would like to take a look at the dataset. Where can it be downloaded? The Snakemake file indicates that it downloaded the fasta from a private repository.

**Comment by emmahodcroft** [comment]
Hi @melop - great! All of the data is available on GISAID - you can go to gisdaid.org to find out more about how to access it. Under the GISAID terms, which protect those who submit the data, we cannot redistribute the data.

If you do find some exclusions that you feel are incorrect, please do let us know! Sometimes sequences are correct/revised later, and may no longer be problematic. At the moment, we are moving so fast it is sometimes hard to find time to re-check these regularly, so if we've missed something, we'd be happy for a heads-up!

Best wishes!

**Comment by melop** [comment]
I could only download sequences at gisaid one by one. Is there a way to perform a batch retrieval?

It is important to make sure that the analysis is repeatable.

Currently a bigger problem is how the tree is rooted. Please see the other issue I opened. 

Before having a reliable root, I suggest displaying only an uprooted tree with only tip dates but no inferred dates for internal nodes, which requires the tree to be rooted.

**Comment by melop** [comment]
And for now, I suggest not exclude based on "confusing phylogeography" or any sequences based on a posteriori inspection of the phylogeny. It seems like a scientific malpractice to enforce the data to fit a predefined biogeography model, which is exactly what's being inferred.

**Comment by tolot27** [comment]
Just to keep things together. One technical reason is if sequences are reverse-complemented (see issue #252).

**Comment by acx01b** [comment]
The number of iceland, uk, usa, australia (those highly using illumina multiplexing) decreased by about 150 each in the last 36h, copying what emma answered about this : 

> we have had to implement subsampling routines because of the size of the dataset. We currently are capping samples at 120 sequences per division, per month, per year. This was previously at 300 until earlier this week.
We are hoping to supplement this very soon with some other features, so that more sequences are visible on other views - we are working on implementing this now.

**Comment by trvrb** [comment]
Closing this issue. We are curating 1000s of sequences a day and believe that a manually annotated `exclude.txt` file is the only sustainable way to handle this. Manual curation is the accepted standard and is what https://cov-lineages.org does as well for example.
