### ISSUE TITLE
Collection dates for the WI-GMF sequences

### ISSUE THREAD

**Issue by niemasd** [nextstrain/ncov#302]
I have been running my own real-time analysis of COVID-19 sequences from GISAID, and I saw that the recent Wisconsin sequences on GISAID had collection YYYY-MM, but no DD, so I reached out to the submitting lab. They are updating their entries on GISAID, but just in case you've already pulled them, I wanted to forward them to you as well.

```
hCoV-19/USA/WI-GMF/00018/2020         3/18/2020
hCoV-19/USA/WI-GMF/00049/2020         3/18/2020
hCoV-19/USA/WI-GMF/00227/2020         3/23/2020
hCoV-19/USA/WI-GMF/00228/2020         3/23/2020           
hCoV-19/USA/WI-GMF/00232/2020         3/23/2020
hCoV-19/USA/WI-GMF/00237/2020         3/23/2020
```

**Comment by emmahodcroft** [comment]
Hi Niema! Thanks for providing these! I've just checked GISAID it seems these dates have been updated, and are now part of our live-build! (We automatically filter out any samples that don't have 'day'.) When possible we like to wait for these changes to filter through from GISAID, so that we don't hard-write over them - if there's every any other changes we then never catch them as our hard-write changes overwrite whatever's coming from GISAID.
However, thanks very much for reaching out to get these - if they hadn't been updated so quickly this would have been really useful!!

We are still missing dates from some WI ones (well - they have dates, but they aren't collection dates, it turns out, but sequencing dates!) so we are excluding these - but as soon as we hear they've updated to collection dates on GISAID they should go back in!
