### ISSUE TITLE
Some mutation data entries don't fit gene / protein sequences

### ISSUE THREAD

**Issue by gtauriello** [nextstrain/ncov#345]
**Current Behavior**  
In an effort to [map mutations from nextstrain onto protein structures](https://github.com/SWISS-MODEL/covid-19-Annotations-on-Structures/pull/24) (experimental and predicted), we observed a couple of mutation entries which seem off.
I list all observed cases below and explain it on a single case: in your ncov.json we can see the entry with "gisaid_epi_isl" == "EPI_ISL_419701" with a mutation labeled "S84L" for "ORF8" and a corresponding "nuc" mutation of "C28144T". If I check the [reference sequence](https://www.ncbi.nlm.nih.gov/nuccore/MN908947), I find that the mutation seems to be flipped as the reference genome has a "T" at pos. 28144 and ORF8 has a "L" at pos. 84.

**Expected behavior**  
I expect the mutations to consistently be in the correct order so that they can be processed well. In the example above it should (probably) be "L84S" instead of "S84L" and "T28144C" instead of "C28144T".

**How to reproduce**  
Explained in "Current Behavior".

**Additional context**  
Here the full list of entries where the mutation seems off with respect to the UniProt sequence they were mapped to. I only manually checked a few of those and the problem could be reduced to a mismatch with the gene / protein sequence from GenBank (so the UniProt mapping didn't introduce any issue). Also all cases seem to be simply flipped as in the example above:
```
P0DTD1,C5865Y,USA/NY-NYUMC40/2020,Maria Aguero-Rosenfeld et al,EPI_ISL_419701 uniprot says: Y
P0DTC8,S84L,USA/NY-NYUMC40/2020,Maria Aguero-Rosenfeld et al,EPI_ISL_419701 uniprot says: L
P0DTD1,V1997A,Netherlands/NoordBrabant_29/2020,Nieuwenhuijse et al,EPI_ISL_414538 uniprot says: A
P0DTD1,F3606L,Nanchang/JX176/2020,Li et al,EPI_ISL_421261 uniprot says: L
P0DTD1,S765P,USA/NY-NYUMC1/2020,Chen et al,EPI_ISL_414639 uniprot says: P
P0DTD1,V739I,Belgium/DV-0324117/2020,Joan Marti-Carreras et al,EPI_ISL_420374 uniprot says: I
P0DTD1,F3606L,Belgium/ULG-7019/2020,Keith et al,EPI_ISL_417025 uniprot says: L
P0DTC2,P943S,Belgium/BJ-030767/2020,Joan Marti-Carreras et al,EPI_ISL_420323 uniprot says: S
P0DTD1,*4379Y,Portugal/PT0090/2020,Guiomar et al et al,EPI_ISL_421493 uniprot says: Y
P0DTD1,T2187N,Netherlands/NA_24/2020,Nieuwenhuijse et al,EPI_ISL_415481 uniprot says: N
P0DTD1,L4715P,Belgium/SB-030990/2020,Joan Marti-Carreras et al,EPI_ISL_420346 uniprot says: P
P0DTC2,G614D,Australia/VIC123/2020,Seemann et al,EPI_ISL_419731 uniprot says: D
P0DTC5,M175T,Belgium/BC-03016/2020,Vanmechelen et al,EPI_ISL_415157 uniprot says: T
P0DTD1,I265T,Senegal/610/2020,Dia et al,EPI_ISL_420075 uniprot says: T
P0DTC3,H57Q,NanChang/JX216/2020,Li jian Xiong et al,EPI_ISL_417420 uniprot says: Q
P0DTC2,G614D,NanChang/JX216/2020,Li jian Xiong et al,EPI_ISL_417420 uniprot says: D
P0DTC3,H57Q,Belgium/BCM-0324160/2020,Joan Marti-Carreras et al,EPI_ISL_420417 uniprot says: Q
P0DTD1,L4715P,USA/NY-NYUMC22/2020,Maria Aguero-Rosenfeld et al,EPI_ISL_418968 uniprot says: P
```
The comma separated list above has "UniProt KB AC,mutation-string,name,author,gisaid_epi_isl" where all data is from your json apart from the UniProt KB AC and a modification of the mutation-string to map ORF1b to P0DTD1. The row is followed by "uniprot says: X" where 'X' is the one-letter-code expected in the protein sequence as stored in UniProt. All the UniProt data is from their [Covid-19 prerelease](https://covid-19.uniprot.org).

**Comment by brianpardy** [comment]
I can't speak to what is "correct" here, but I think what you are describing here is a result of back-mutations along the tree.  The EPI_ISL_419701 sequence that you noted is deep within the ORF8  L84S T28144C branch early in the phylogeny, and then this sequence bears a back-mutation/reversion ORF8 S84L C28144C.

Nucleotide and amino acid changes in nextstrain appear to be reported relative to each sequence's position in the containing phylogenetic tree, not relative to the reference sequence.

The ORF1A L3606F/F3606L is another mutation flipping back and forth repeatedly in the tree so I suspect the same applies to the sequences on your list at that location.  I haven't checked on the other sequences you listed.

**Comment by emmahodcroft** [comment]
I haven't checked all of the examples lists, but in position 28144, @brianpardy is correct! On this sequence (and some others) the virus seems to (from reconstruction) have a 'T' at this position ancestrally, but has then mutated along one clade to have a 'C' - then in some sequences mutated back to being a 'T':
![image](https://user-images.githubusercontent.com/14290674/78825224-e1222280-79df-11ea-9345-c61ce38b8409.png)

Because we reconstruct these sequences (and protein sequences) ancestrally along the tree as part of the analyses, we always show the mutations with respect to the branch they come from. So, the best way to ensure you are gathering the correct set of mutations for a sequence, you should start at the base of the tree and traverse up to the tips, recording the mutations along the way. Alternatively, you could compare the sequences themselves to the reference, to see what has mutated relative to this!

Also important to note is that since we reconstruct an 'ancestor' to all the sequences, and all mutations are relative to this, our mutations are *not* relative to the reference - we just use this for alignment, and then for determining where genes lie (by coordinates). All mutations are instead relative to this reconstructed 'ancestral' sequence :)

I hope this helps! Thank you so much for such making such a detailed issue!

**Comment by gtauriello** [comment]
Thank you both very much for the detailed explanation and my apologies for wrongly classifying this as a bug. I still find it striking though that all those mutations, where the mutated residues didn't match the reference, ended up being back-mutations.

Anyways, I shall remove the "BUG" from the title and close this issue. Thanks again and keep up the great work you are doing.

**Comment by emmahodcroft** [comment]
@gtauriello I'm so glad this was helpful! It's not too unexpected that those that are back-mutations are also those who 'mismatch' the reference (or, I suppose, they *do* match the reference, thus the 'mutation' seems backwards), as our reference is from the beginning of the epidemic, so close to the root. However, in general this may not *always* be the case (for example, in Enterovirus D68 runs, the reference is *not* close to the root), so how much these two things match up will vary across different builds. I hope that helps make sense of the pattern!
