### ISSUE TITLE
[BUG] Selected continent is still shown in legend

### ISSUE THREAD

**Issue by Maijin** [nextstrain/ncov#350]
**Current Behavior**  
Continent is shown in the legend when a specific continent dataset is selected 

**Expected behavior**  
Continent isn't shown in the legend when a speicfic continent dataset is selected 

**How to reproduce**  
Steps to reproduce the current behavior:  
1. Open https://nextstrain.org/ncov/europe 
2. Observe Europe is shown in the legend

<img width="85" alt="image" src="https://user-images.githubusercontent.com/1408600/78980390-17fe5280-7b1e-11ea-9d20-382bf2e331cd.png">

**Your environment: if browsing Nextstrain online**  
 - Operating system:  Mac OS
 - Browser:  Firefox

**Comment by jameshadfield** [comment]
Hi @Maijin -- while the European build (https://nextstrain.org/ncov/europe) is focused on samples from Europe, it's important to provide context of closely linked genomes to avoid misinterpretation. This is why we include samples from other regions (and we try to be smart about the non-European samples we include).

**Comment by Maijin** [comment]
Ok it just look weird to have countries of europe + europe in the same legend see -

<img width="344" alt="image" src="https://user-images.githubusercontent.com/1408600/78983371-6282cd80-7b24-11ea-918a-be2f35371c4e.png">

**Comment by Maijin** [comment]
@jameshadfield the issue isn't to have africa etc in the legend but to have both countries of europe AND "Europe" in the same legend see -

![image](https://user-images.githubusercontent.com/1408600/78985201-76c8c980-7b28-11ea-97df-0135cc7af0ea.png)

**Comment by jameshadfield** [comment]
Ahh - I see. This may be a bug then

**Comment by emmahodcroft** [comment]
I had a brief look into this and it seems like it might be caused by those with travel exposure to Europe, but who were sampled in non-European countries.

(@jameshadfield  in `results/metadata_adjusted_Europe.tsv` search for `Europe\tEurope`)

This may indicate we need to modify our 'travel history' scripts to handle this properly.

**Comment by emmahodcroft** [comment]
Alternatively, something in one of our 'colour cleanup' scripts isn't cleaning up exactly as it should!

**Comment by jameshadfield** [comment]
You're correct @emmahodcroft -- this is caused by a genome with a region outside the focal region, but with a `region_exposure` equal to the focal region (e.g. Europe, in the above example). `adjust_regional_meta.py` modifies this samples' `country_exposure` to be `region_exposure` (Europe) and that results in what we see above. 

This isn't present on a tip, but rather an internal branch with a simgle tip as a child (via `modify-tree-according-to-exposure.py`).

One solution would be to improve `adjust_regional_meta.py` to not overwrite the sample's `country_exposure` if the `region_exposure` is the current focal region. This should add usable information for the DTA.

**Comment by trvrb** [comment]
I'm going to keep this issue open but label as "low priority".

**Comment by Maijin** [comment]
@trvrb this is fixed actually 👍 see

<img width="303" alt="image" src="https://user-images.githubusercontent.com/1408600/105477967-ddc40300-5ca2-11eb-89ff-a96646dfe9bf.png">
