### ISSUE TITLE
[BUG] mafft run fails in augur: mafft upgrade and modification of pipeline suggested

### ISSUE THREAD

**Issue by NGSCBIGithub** [nextstrain/ncov#382]
**Current Behavior**  
>> ERROR: b''
>> shell exited 1 when running: mafft --reorder --anysymbol --nomemsave 
>> --adjustdirection --thread 2 
>> results/split_alignments/11.fasta.to_align.fasta 1> 
>> results/split_alignments/11.fasta 2> 
>> results/split_alignments/11.fasta.log

**Expected behavior**  
The alignment step should work fine.

**Your environment: if running Nextstrain locally**  
 Linux ip-10-31-66-151 4.15.0-1065-aws #69-Ubuntu SMP Thu Mar 26 02:17:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**  
 mafft author (Kazutaka Katoh <katoh@ifrec.osaka-u.ac.jp>) suggests upgrading mafft to most recent version. This would entail the following change in mafft command

1. To use the new option, necessary to change the command-line option
From:
> mafft --reorder --anysymbol --nomemsave --adjustdirection --thread 2

To:
> mafft --reorder --anysymbol --auto --addfragments othersequences 
> --thread 2 referencesequence > output

**Comment by tsibley** [comment]
@NGSCBIGithub Thanks for the bug report. A description of the environment you're running in and the complete log output is necessary to effectively troubleshoot this. There are a variety of reasons why mafft may exit 1 with the short log output you quoted.

Note that the command-line change you propose fundamentally changes how mafft performs the alignment; it's not a functionally-equivalent change.

**Comment by Addicted-to-coding** [comment]
Hi,
I'm getting the exact same error when I try to run the example data. I'm running it using the nextstrain environment. Here's the complete error message I get, which is also present in the log files.
        augur align             --sequences results/split_sequences/1.fasta             --reference-sequence config/reference.gb             --output results/split_alignments/1.fasta             --nthreads 2             --remove-reference 2>&1 | tee logs/align_1.txt
        

ERROR: b''
shell exited 1 when running: mafft --reorder --anysymbol --nomemsave --adjustdirection --thread 2 results/split_alignments/1.fasta.to_align.fasta 1> results/split_alignments/1.fasta 2> results/split_alignments/1.fasta.log


using mafft to align via:
	mafft --reorder --anysymbol --nomemsave --adjustdirection --thread 2 results/split_alignments/1.fasta.to_align.fasta 1> results/split_alignments/1.fasta 2> results/split_alignments/1.fasta.log 

	Katoh et al, Nucleic Acid Research, vol 30, issue 14
	https://doi.org/10.1093%2Fnar%2Fgkf436

Error during alignment
[Mon Jun  8 09:50:02 2020]
Error in rule align:
    jobid: 27
    output: results/split_alignments/1.fasta
    log: logs/align_1.txt (check log file(s) for error message)
    shell:
        
        augur align             --sequences results/split_sequences/1.fasta             --reference-sequence config/reference.gb             --output results/split_alignments/1.fasta             --nthreads 2             --remove-reference 2>&1 | tee logs/align_1.txt
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job align since they might be corrupted:
results/split_alignments/1.fasta
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /u/scratch/m/mdistler/covid/ncov/.snakemake/log/2020-06-08T094944.275161.snakemake.log

Could you please help with this?

**Comment by erinyoung** [comment]
From what I've observed, it's a memory error. 

I have 251G of memory, but when I try to align ~2500+ SARS-CoV-2 sequences, mafft has issues. 

I've been able to avoid this by aligning a subsection of my sequences prior to the nextstrain build command and changing the augur align rule in the Snakefile to

```
 augur align \
--sequences {input.sequences} \
--reference-sequence {input.reference} \
--output {output.alignment} \
--nthreads {threads} \
--existing-alignment {params.existing} \
--fill-gaps
```

where {params.existing} is the pre-aligned multifasta of a subsection of the sequences. 

mafft also has a `--large` option that creates temp files instead of saving everything to RAM

**Comment by xieruopeng** [comment]
> From what I've observed, it's a memory error.
> 
> I have 251G of memory, but when I try to align ~2500+ SARS-CoV-2 sequences, mafft has issues.
> 
> I've been able to avoid this by aligning a subsection of my sequences prior to the nextstrain build command and changing the augur align rule in the Snakefile to
> 
> ```
>  augur align \
> --sequences {input.sequences} \
> --reference-sequence {input.reference} \
> --output {output.alignment} \
> --nthreads {threads} \
> --existing-alignment {params.existing} \
> --fill-gaps
> ```
> 
> where {params.existing} is the pre-aligned multifasta of a subsection of the sequences.
> 
> mafft also has a `--large` option that creates temp files instead of saving everything to RAM

Yes. I totally agree with you.

**Comment by huddlej** [comment]
This issue has been [resolved by v5 of the workflow when we switched from mafft to nextalign](https://github.com/nextstrain/ncov/blob/master/docs/change_log.md#v5-7-may-2021).
