### ISSUE TITLE
Missing color schemes

### ISSUE THREAD

**Issue by biocyberman** [nextstrain/ncov#386]
Max length  (number of lines) for the current color is 500. While the traits has total 503. So this line is failing:
https://github.com/nextstrain/ncov/blob/e819f38279aa6f74f896ae01d5ff9282d63bd1f5/scripts/assign-colors.py#L59

**Comment by emmahodcroft** [comment]
Hi @biocyberman, thanks for reaching out! For which trait is there more than 503 colours?

**Comment by biocyberman** [comment]
You can run and see the error:

`python3 ncov/scripts/assign-colors.py --ordering ncov/config/ordering.tsv --color-schemesncov/config/color_schemes.tsv --output colors.tsv`

**Comment by biocyberman** [comment]
And sorry for the ambiguous report at the start :)

**Comment by emmahodcroft** [comment]
Hi @biocyberman, I'm sorry the error message is vague - not sure why it's giving you this error - however, the problem should be solved by passing in the metadata file as well, rather than just the three arguments you have at the moment. See how it's called [in the Snakefile](https://github.com/nextstrain/ncov/blob/master/Snakefile#L428) for an example. 

Otherwise, yes, there are too many traits!
I hope that helps!

**Comment by biocyberman** [comment]
That's what I ended up doing :) Haven't got time to push  addition locations and divisions for Denmark.
