### ISSUE TITLE
Tree building failed problem

### ISSUE THREAD

**Issue by ripendil-bd** [nextstrain/ncov#425]
Hi, Sorry to bother, I am new to this. I was trying to build a phylogeny tree from GISAID data using nextstrain-cli in MacOS terminal. After running the build overnight the tree building failed showing following error: 
ERROR: TREE BUILDING FAILED
Please see the log file for more details: results/global/subsampled_alignment-delim.iqtree.log

Building original tree took 5567.713834762573 seconds
[Thu Jun  4 00:18:22 2020]
Error in rule tree:
    jobid: 13
    output: results/global/tree_raw.nwk
    log: logs/tree_global.txt (check log file(s) for error message)
    shell:
        
        augur tree             --alignment results/global/subsampled_alignment.fasta             --output results/global/tree_raw.nwk             --nthreads 4 2>&1 | tee logs/tree_global.txt
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /nextstrain/build/.snakemake/log/2020-06-03T183616.959182.snakemake.log
-----------
I checked the subsampled_alignment-delim.iqtree.log file and found many identical sequences. Probably this is not a new issue. I checked older issues and found a solution of running the normalize_gisaid_fasta.sh script. But that did not solve the problem.

Please suggest me what to do. I just need to build a tree using sequences submitted from Bangladesh compared with global sequences (The online nexstrain version shows only a subset of sequences)

Sorry if this issue seems dumb, I am new to this, please help!

**Comment by jameshadfield** [comment]
Hi @ripendil-bd -- could you post the `logs/tree_global.txt` to look at?

**Comment by ripendil-bd** [comment]
> Hi @ripendil-bd -- could you post the `logs/tree_global.txt` to look at?

Hi @jameshadfield , thank you for replying,
here is the tree_global.txt text:
ERROR: b'/bin/bash: line 1: 89111 Killed                  iqtree -ninit 2 -n 2 -me 0.05 -nt 4 -s results/global/subsampled_alignment-delim.fasta -m GTR > results/global/subsampled_alignment-delim.iqtree.log\n'
shell exited 137 when running: iqtree -ninit 2 -n 2 -me 0.05 -nt 4 -s results/global/subsampled_alignment-delim.fasta -m GTR  > results/global/subsampled_alignment-delim.iqtree.log

Building a tree via:
	iqtree -ninit 2 -n 2 -me 0.05 -nt 4 -s results/global/subsampled_alignment-delim.fasta -m GTR  > results/global/subsampled_alignment-delim.iqtree.log
	Nguyen et al: IQ-TREE: A fast and effective stochastic algorithm for estimating maximum likelihood phylogenies.
	Mol. Biol. Evol., 32:268-274. https://doi.org/10.1093/molbev/msu300

ERROR: TREE BUILDING FAILED
Please see the log file for more details: results/global/subsampled_alignment-delim.iqtree.log

Building original tree took 5567.713834762573 seconds

**Comment by tsibley** [comment]
It appears the tree builder iq-tree was forcibly stopped by your operating system, likely for running out of memory. In our runs, the global tree building uses about 4-6 GiB of memory, so you should have more than that available. How much is used will also vary depending on how you're running the workflow.

The log file `results/global/subsampled_alignment-delim.iqtree.log` might have more details as well from iq-tree itself, if you could post it.

**Comment by ripendil-bd** [comment]
> It appears the tree builder iq-tree was forcibly stopped by your operating system, likely for running out of memory. In our runs, the global tree building uses about 4-6 GiB of memory, so you should have more than that available. How much is used will also vary depending on how you're running the workflow.
> 
> The log file `results/global/subsampled_alignment-delim.iqtree.log` might have more details as well from iq-tree itself, if you could post it.

Hi @tsibley , here is the file
[subsampled_alignment-delim.iqtree.log](https://github.com/nextstrain/ncov/files/4733989/subsampled_alignment-delim.iqtree.log)

**Comment by tsibley** [comment]
Thanks @ripendil-bd. The top of that log file shows that iq-tree only has access to 1GB of memory:

```
Host:    9c04632ec02c (AVX2, FMA3, 1 GB RAM)
Command: iqtree -ninit 2 -n 2 -me 0.05 -nt 4 -s results/global/subsampled_alignment-delim.fasta -m GTR
Seed:    913607 (Using SPRNG - Scalable Parallel Random Number Generator)
Time:    Wed Jun  3 22:45:39 2020
Kernel:  AVX+FMA - 4 threads (4 CPU cores detected)
```

Running the global build with the default subsampling parameters will require more memory than that.

I suspect that your computer probably has more memory than that available but that by default the container the `nextstrain build` command uses is not allowed to access it. If you run `nextstrain check-setup`, it will likely report a warning about memory. You can adjust the memory available to Docker containers in the Docker for Mac preferences.

**Comment by jmtembo** [comment]
Hello I have the very same problem but I didnt use docker to install nextstrain I used the command line to do it. Do I need to install docker and then adjust memory available to containers? Is there a way I can do this without installing docker?

**Comment by jmtembo** [comment]
Hello @tsibley  I have the very same problem but I didnt use docker to install nextstrain I used the command line to do it. Do I need to install docker and then adjust memory available to containers? Is there a way I can do this without installing docker?

**Comment by tsibley** [comment]
@jmtembo Could you share exactly which commands you're running and the exact error message you're seeing?

**Comment by jmtembo** [comment]
Hello thanks @tsibley below is what I get when trying to run a build

(nextstrain) johntembo@Johns-MacBook-Air ncov-9 % snakemake --profile my_profiles/phylogeny -p
Config file defaults/parameters.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job stats:
job                         count    min threads    max threads
------------------------  -------  -------------  -------------
aa_muts_explicit                1              1              1
add_branch_labels               1              1              1
adjust_metadata_regions         1              1              1
all                             1              1              1
ancestral                       1              1              1
calculate_epiweeks              1              1              1
clades                          1              1              1
colors                          1              1              1
distances                       1              1              1
emerging_lineages               1              1              1
export                          1              1              1
finalize                        1              1              1
include_hcov19_prefix           1              1              1
logistic_growth                 1              1              1
mutational_fitness              1              1              1
recency                         1              1              1
refine                          1              1              1
rename_emerging_lineages        1              1              1
tip_frequencies                 1              1              1
traits                          1              1              1
translate                       1              1              1
tree                            1              4              4
total                          22              1              4

Select jobs to execute...

[Wed Dec 15 11:20:08 2021]
Job 6: Building tree


        augur tree             --alignment results/default-build/aligned.fasta             --tree-builder-args '-ninit 10 -n 4'             --output results/default-build/tree_raw.nwk             --nthreads 4 2>&1 | tee logs/tree_default-build.txt
        
WARNING: more threads requested than there are sequences; falling back to IQ-TREE's `-nt AUTO` mode.

ERROR: Shell exited 2 when running: iqtree2 -ninit 2 -n 2 -me 0.05 -nt AUTO -s results/default-build/aligned-delim.fasta -m GTR -ninit 10 -n 4 > results/default-build/aligned-delim.iqtree.log
Command output was:
  OMP: Info #271: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
  ERROR: Cannot read file results/default-build/aligned-delim.fasta

Building a tree via:
	iqtree2 -ninit 2 -n 2 -me 0.05 -nt AUTO -s results/default-build/aligned-delim.fasta -m GTR -ninit 10 -n 4 > results/default-build/aligned-delim.iqtree.log
	Nguyen et al: IQ-TREE: A fast and effective stochastic algorithm for estimating maximum likelihood phylogenies.
	Mol. Biol. Evol., 32:268-274. https://doi.org/10.1093/molbev/msu300

ERROR: TREE BUILDING FAILED
Please see the log file for more details: results/default-build/aligned-delim.iqtree.log

Building original tree took 0.022847890853881836 seconds
Waiting at most 5 seconds for missing files.
MissingOutputException in line 1158 of /Users/johntembo/ncov-9/workflow/snakemake_rules/main_workflow.smk:
Job Missing files after 5 seconds:
results/default-build/tree_raw.nwk
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Job id: 6 completed successfully, but some output files are missing. 6
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/johntembo/ncov-9/.snakemake/log/2021-12-15T112006.591122.snakemake.log
