### ISSUE TITLE
Inconsistency in lat_longs.tsv and ordering.tsv data?

### ISSUE THREAD

**Issue by biocyberman** [nextstrain/ncov#433]
I am checking the file and see that only `Asia` has `region` definition on this line:
https://github.com/nextstrain/ncov/blob/master/config/lat_longs.tsv#L1596
Other continents do not have this. They still have `country` and `division`. 

```
grep -n 'region' lat_longs.tsv
1607:region     Asia    30.451098       86.654576

grep -n 'Europe\|North America' lat_longs.tsv
1061:division   Europe  49.646237       10.799454
1290:division   North America   28.2367447      -97.738017
1601:country    Europe  49.646237       10.799454
1602:country    North America   28.2367447      -97.738017
```

Whereas in ordering.tsv: 

```
grep -n 'region' ordering.tsv
1652:region     Asia
1653:region     Oceania
1654:region     Africa
1655:region     Europe
1656:region     South America
1657:region     North America
```
I can fix this but need to understand the intention first.  By the way, I guess it maybe because some samples do not have higher resolution data, so continents are taken as countries. But this caused confusion and doubts about data integrity when I see those entries.

**Comment by emmahodcroft** [comment]
Hi @biocyberman - good spotting! This is a little confusing, but actually isn't an inconsistency. Any run using `augur` can benefit from the lat-long locations for 'region' and 'country' which we store within the `augur` program itself:
https://github.com/nextstrain/augur/blob/master/augur/data/lat_longs.tsv

However, in most of our runs, we split Asia into 'South Asia', 'West Asia' and 'Southeast Asia'. For the `ncov` runs, we just have 'Asia'. Thus, we needed to provide a 'new' lat-long to explain where 'Asia' is. By supplying our own lat-long file we simply build upon what's already in the `augur` file. This is also why you'll see not *all* countries in the `ncov` lat-long file - because many are included already in `augur`.

I hope that makes sense!

The `orderings.tsv` file is what we use to generate colorings. Thus, everything we want a coloring for needs to be in this file - we don't have any files in `augur` which perform a similar function (this is much more personalised to a build). That's why all the regions, and all the countries (and divisions, locations) will have an entry in `orderings.tsv`.

However, good spotting, and I hope this clarifies this somewhat deceptive arrangement!

**Comment by emmahodcroft** [comment]
Ah sorry, and to your last point - yes, the reason we often have regions & countries as lower-level entries in the `orderings.tsv` file is because of lack of higher-resolution data. This is intentional and doesn't need to be modified!

**Comment by biocyberman** [comment]
Thank you for clarification and confirmation, Emma. I feel safe when you and the team do that intentionally :) We have been keeping the these data for denmark in our local copy of the repo. I think it's time we send PR so we don't have to merge anytime the upstream has update on this. 

I propose the merging command like the following. It will change the order of lines in current files, but will make a breeze to add new data:  

```
cat latlong_denmark.tsv lat_longs.tsv |sort -k1,1 -k2,2 |uniq >lat_longs.all.tsv
{ cut -f 1,2 latlong_denmark.tsv; cat ordering.tsv; } |sort -k1,1 -k2,2 |uniq >ordering.all.tsv

mv ordering.all.tsv ordering.tsv
mv lat_longs.all.tsv lat_longs.tsv
```
The reason I propose this: I was trying to fit the lines for Denmark into correct order following upstream convention. But this takes time and is error prone.

**Comment by emmahodcroft** [comment]
Hi @biocyberman ! What I would suggest is that you add a rule to your own versions of the runs - you can make your own profile for example, which can incorporate additional rules containing rules (see more information in the docs [here](https://github.com/nextstrain/ncov/blob/master/docs/running.md#configuring-your-build) - and also look at the `nextstrain` profile in the `ncov` build for an idea of how to do this!). You can then make one of your rules be to `cat` your own lat-long/orderings file with ours!

While we're always keen to keep the lat-long information up-to-date and correct for the sequences we have, we unfortunately don't have extra location information for Denmark below country level, so we would not include this in our own files.

We use and modify these files daily as part of maintaining our runs, so we try to keep these very tidy and organised to what's used in the builds. The order of the lat-longs file is more obvious - by section, it's alphabetical. The order of `orderings.tsv` is more cryptic - this is the order that things show up in the legend on the website, so this order is geographic - though we admit that for the very long categories, this can be hard to tell! As we merge future PRs that let the legend change with zoom and filter, this aspect will be more visible!

I hope all this makes sense, and wish you success in setting up your own profile & rule which will let you easily maintain both your own lat-longs and keep up with ours!

**Comment by biocyberman** [comment]
> While we're always keen to keep the lat-long information up-to-date and correct for the sequences we have, we unfortunately don't have extra location information for Denmark below country level, so we would not include this in our own files.

@emmahodcroft  Would it make sense I send a PR for this, or a separate lat_long data for Denmark?

**Comment by emmahodcroft** [comment]
@biocyberman We wouldn't generally incorporate the detailed lat-long data for Denmark into the `ncov` repo, since we don't have those locations (for us it would be 'extra data' that we can't use!). What I'd suggest is to keep this just in your own repo. 

However, it would be easy to add a rule to your own runs (are you using `profiles`?) so that one of your first steps is `cat`-ing this Denmark-specific file to the `ncov` `config/lat_longs.tsv` file - then it'll be easy to stay up-to-date with the `ncov` build, but also have your own locations!

I hope that helps!

**Comment by biocyberman** [comment]
> We wouldn't generally incorporate the detailed lat-long data for Denmark into the ncov repo, since we don't have those locations (for us it would be 'extra data' that we can't use!). 

@emmahodcroft  I thought about updating the upsteam `ncov` repo with Denmark locations because I could see there are locations for cities around the world. It's only cities and municipalities of Denmark, not higher resolution than that. Are these still not suitable for upstream `ncov`?   Further more, we also submitted data to GISAID. So you (your team) will deal with Denmark data anyway? Or maybe I am missing something still? 

>  it would be easy to add a rule to your own runs (are you using profiles?) so that one of your first steps is cat-ing this Denmark-specific file to the ncov config/lat_longs.tsv file - then it'll be easy to stay up-to-date with the ncov build, but also have your own locations!

That's what I am doing. And yes, I managed to build a local instance with denmark profile and `builds` I want. However, I am still wondering whether I should add something beside lat_longs data. For example, a location is mentioned in three files: 

```bash
ack "East Feliciana Parish" ./config/
config/ordering.tsv
344:location    East Feliciana Parish

config/colors_global.tsv
311:location    East Feliciana Parish   #E67331

config/lat_longs.tsv
344:location    East Feliciana Parish   30.850463       -91.036298
```

**Comment by emmahodcroft** [comment]
> @emmahodcroft I thought about updating the upsteam ncov repo with Denmark locations because I could see there are locations for cities around the world. It's only cities and municipalities of Denmark, not higher resolution than that. Are these still not suitable for upstream ncov? Further more, we also submitted data to GISAID. So you (your team) will deal with Denmark data anyway? Or maybe I am missing something still?

Sorry, I think I haven't explained very well! So yes, we do take location (city usually) and division-level (county/state/canton) data. However, for all the Denmark samples we have, we have no information at these levels - only country. So this is why we don't have any Danish locations or divisions, and why we wouldn't add these at this time. We only include locations/divisions/countries where we have that data attached to some kind of sequence. Since for the Denmark sequences they only have 'Denmark' - then we only have 'Denmark' included.

If we get data which has lower-level Denmark data, then we will be happy to include the corresponding information for these! However, until we do, we don't add data which isn't attached to a sequence. Of course, we'd love if the Danish sequences were updated with more geographic info (if allowed) and would then be very happy to add this to our `lat_longs` & `orderings` files! Until then, though, you are best to `cat` as you are doing.

>However, I am still wondering whether I should add something beside lat_longs data. For example, a location is mentioned in three files:

Yes - and sorry if this isn't clear either! You should add additional locations and divisions to `orderings.tsv`. These are loosely in Geographical order, so that locations within a country are near others within that same country - etc. This is the file that's used to generate `colors_global.tsv` - so you don't need to add anything to this file - if it's in `orderings.tsv` it'll end up in here too.

I hope that helps!

**Comment by biocyberman** [comment]
Crystal clear! Thanks @emmahodcroft. I learnt too that it is not legally possible to input coordinate lower than country level for Denmark because of small sample size and small population. It would risk making the info become traceable to individuals hence violating GDPR. So it is what it is for now, and I will keep working on our local copy. Thanks again for very helpful answers, as always.

**Comment by emmahodcroft** [comment]
Wonderful, I'm glad this helped! Yes, there's lots of different restrictions on data protection, so sometimes this is not possible. If you ever end up conglomerating on a larger scale (New Zealand ended up creating much larger over which they cluster cases, for same reason) feel free to let us know, and we can incorporate those too! (Of course, if they're made up, you'll have to tell us the lat-longs!)
