### ISSUE TITLE
[BUG] clade analysis

### ISSUE THREAD

**Issue by yhkim1006** [nextstrain/ncov#439]
Hi. I have a question about clade analysis.
I get the GISAID metadata & fasta and run the neststrain pipeline. 
Running pipeline is good but I was confused some clade results.

According to the clade.tsv file in /config/ directory , 19A has C allele at position 8782.
However, as a result of GISAID samples (using nextstrain pipeline), a sample have T allele in 8782 position but clade results is 19A.

Is the clade calculation method different from matching allele with clade.tsv?
If you know a detailed method, I would be grateful if you could give me a reference.

thanks

**Comment by rneher** [comment]
I think we need more detail to answer your question. which specific isolate are you referring to? Did you use the `assign_clades.py` script or the `augur clades` command? 

It is possible that individual strains within a clade back-mutate at this position.

**Comment by yhkim1006** [comment]
@rneher 
I just run the "build ncov" with GISAID fasta and metadata of 37134 samples. and I get the results in /results/global/clades.json.
I thought the 19A must has C allele at position 8782 because config/clade.tsv has that.
but some samples have T allele at 8782 position but results is 19A.
I wonder why the samples results is 19A although having T allele at 8782 position.

below is clade.tsv text for 19A.
--------------------------------------------------------------------
clade	gene	site	alt
19A	nuc	8782	C
19A	nuc	14408	C
--------------------------------------------------------------------

Is it correct to calculate the clade as below?

8782 (C) -> 14408 (C) -> 19A
8782 (C) -> 14408 (T) -> other clade
8782 (T) -> ... -> other clade

![image](https://user-images.githubusercontent.com/66615115/85083695-75dda380-b20d-11ea-87b6-0f536253b75e.png)

**Comment by biocyberman** [comment]
@yhkim1006  I wish it can be simple binary tree like that. The core function to decide a sequence belong to a clade is [`is_node_in_clade`](https://github.com/nextstrain/augur/blob/master/augur/clades.py#L45) and the `asing_clade` function in the same file. I guess depending on tree topology of the refine tree, there would be something unexpected. The refine tree has been causing me confusion several times.

**Comment by emmahodcroft** [comment]
The full list of SNPs that confer a clade can be found at https://github.com/nextstrain/ncov/blob/master/config/clades.tsv

However, @biocyberman is correct that for `augur clades` this is done along a phylogenetic tree. So, we do not decide individually for each sequence based on the SNPs what clade it is in, but rather we do this along the whole tree. 

So, we as traverse the tree from root to tip, we essentially assign all nodes 'below' that current tip to be the clade that was 'last' assigned. This only changes if we come to a node that has *all* of the required mutations in order to assign it to another clade. 

So, from the root, all tips will be initially assigned to '19A'. They will *only* change if we find a node that has all the required mutations to be considered another clade. This is important because back-mutation (or mutation) is always an issue. You can see that even though we use 8782T to define '19B' - there will be other sequences that have this mutation: https://nextstrain.org/ncov/global?c=gt-nuc_8782
![image](https://user-images.githubusercontent.com/14290674/85200869-1cec3900-b2fb-11ea-8891-734aef61a947.png)


So, strictly, one cannot look at mutations lone to predict clades, and clades alone cannot predict mutations (though in both cases, this will be *largely* true). 

In our `assign_clades.py` script, because making trees is expensive (computationally) and takes time, we _do_ just use the SNPs to predict clades. However the most reliable way to get the clades is to run `augur clades`.

I hope all this helps!

**Comment by biocyberman** [comment]
A clarification related to this issue, if it is OK: This line https://github.com/nextstrain/augur/blob/master/augur/clades.py#L71 means that` is_node_in_clade` relaxes requirement to minimum one mutation from the node, at requires only no other conflicting mutations for the remaining mutations in the clade. Why is that? @rneher You are in the "blame" list, maybe you could clarify why it is necessary to do that. 

Further more, this would lead to "draw" cases where the matched mutation happens to be the common mutation among clades. For example, if a node has only one mutation for 19A and 20B: nuc 8782 C. Which clade will it be?

**Comment by emmahodcroft** [comment]
Hi @biocyberman - not sure I'm following here. This line is just to get the allele at a given position in the node being inspected - if that node does not have a mutation at that location, it gets the state from the reference alignment. Then, all the relevant positions are used to determine if they match the definition of the clade (at https://github.com/nextstrain/augur/blob/master/augur/clades.py#L75). 

What we're doing here is determining the 'ancestor' of a clade. This is node that's labelled in writing on the nextstrain.org/ncov tree - the 'start' of the clade, if you will. For a node to be labelled in this way (we call this `clade_annotation`), they must have *all* the mutations present that define a clade. 

From there, we then take all descendants of the `clade_annotation` node (the 'ancestor' of that clade), and they are labelled as being part of that clade, even if they have back mutations. This is why our clade approach is a phylogenetic one rather than a sequence-based one - and why results may differ slightly than from using the `assign_clades.py` script. However, do try to pick sites to define clades where there does not seem to be a lot of arbitrary mutations in the tree.

Of course, if there is another `clade_annotation` nested within a clade, the nodes below this one will belong to that clade.

I hope that makes sense!

**Comment by biocyberman** [comment]
Thanks for the elaboration @emmahodcroft I realized too that it was a false interpretation of the code with minimum one mutation after looking more closely into the function. I am working on a script to resolve sub-clade below the basice clades defined in `config/clades.tsv`. Would need your comment tomorrow or soon enough when I push the script to my fork.

**Comment by rneher** [comment]
@biocyberman we are planning to add subclades via a clade watchlist. In fact, I opened PR #440 a few days ago. this defines a few additional clades (not official yet) and addes them as a color-by to the tree. Is this what you had in mind?

**Comment by rneher** [comment]
this is no longer relevant. clades are implemented differently now
