### ISSUE TITLE
NextStrain Visualization, clades issues

### ISSUE THREAD

**Issue by shashibioinfo143** [nextstrain/ncov#471]
Hi @emmahodcroft 

I have done Analysis for 837 SARS-CoV2 Indian Samples taken from GIASAID.

i have follwed with you related to the errors which i had before hope you remember.

from the interpretation of Nextstrain what i can see is all the 837 data is coming into clades Clades 19A, 19B, 20A, 20B, 20C but in the clades list i have other clades information A1a, A2, A2a, A3, A6, A7, B, B1, B2, B4. (PFA)

from where we can update the clades .tsv files?

One more issue is in the Transmissions section i cant play with individual samples location but it was mentioned in metadata.tsv file.

and one more thing in Diversity section i cant see the mutations falling into category wise.

final queries related to colours.tsv file i have given input file as color_schemes.tsv but in the output i got message like all the colours has not been loaded. is this the correct file 
[files.zip](https://github.com/nextstrain/ncov/files/4929071/files.zip)

![Screenshot from 2020-07-09 20-38-38](https://user-images.githubusercontent.com/54669756/87622264-608e6300-c740-11ea-9c21-2bde3c5f18d5.png)
![Screenshot from 2020-07-09 20-38-24](https://user-images.githubusercontent.com/54669756/87622278-67b57100-c740-11ea-9bb7-25333b60daa7.png)

if you help me to resolve this issue

thank you

**Comment by shashibioinfo143** [comment]
Need help.
please do reply on above issue

**Comment by emmahodcroft** [comment]
Hi @shashibioinfo143 - sorry for the delay! 

>from the interpretation of Nextstrain what i can see is all the 837 data is coming into clades Clades 19A, 19B, 20A, 20B, 20C but in the clades list i have other clades information A1a, A2, A2a, A3, A6, A7, B, B1, B2, B4. (PFA)
from where we can update the clades .tsv files?

You should be able to pull the latest version of the `ncov` repo to update this file - we made this change a little while ago. By ensuring you have the latest copy of this file this should fix itself. Alternatively you can find an up to date copy of the file here: https://github.com/nextstrain/ncov/blob/master/defaults/clades.tsv

>One more issue is in the Transmissions section i cant play with individual samples location but it was mentioned in metadata.tsv file.
and one more thing in Diversity section i cant see the mutations falling into category wise.

I'm afraid I don't know what you mean here - can you try and explain further? If for the first you mean samples aren't showing up on the map, you should ensure the locations you've provided are in the [lat-longs file](https://github.com/nextstrain/ncov/blob/master/defaults/lat_longs.tsv)

>final queries related to colours.tsv file i have given input file as color_schemes.tsv but in the output i got message like all the colours has not been loaded. is this the correct file

For this, I'll need to know a bit about what you're basing your run on. In general, the `ncov` pipeline automatically creates a file in  the respective `results` folder called `colors.tsv` (ex: `results/global/colors.tsv`) which is what's used by export. If you want to set this totally manually, you can direct the `augur export` call to use the `colors.tsv` that you want. Otherwise, if you are using a build based on [our tutorial](https://nextstrain.github.io/ncov/index), you should be able to provide a custom color file to the `builds.yaml` file - as described [here](https://nextstrain.github.io/ncov/customizing-visualization)

I hope this helps!

**Comment by trvrb** [comment]
Hi @ shashibioinfo143. I hope Emma was able to help you resolve these issues. Also, the latest `ncov` repo has better customization options (https://docs.nextstrain.org/en/latest/tutorials/SARS-CoV-2/steps/customizing-analysis.html). I'm going to close this issue now, but please feel free to re-open if you have further questions.
