### ISSUE TITLE
[docs/feature request] How can I draw transmission lines for geographic resolution higher than country 

### ISSUE THREAD

**Issue by marqsbla** [nextstrain/ncov#472]
I want to draw transmission lines for admin. divisions and locations. I can't though. I also can't find any information about it in the documentation. I started to read the JS code but failed to find a solution in a reasonable time. 
Is this something that should be calculated during the build process? Are there any options to be enabled for that? Or transmission lines are just hard-coded for the resolution of a country?

**Comment by jameshadfield** [comment]
I'll comment on the auspice side of things (since you mention reading the JS code), but leave the instructions for how to do this for your particular nCoV build to others. 

The best documentation is [here](https://nextstrain.org/docs/visualisation/map-interpretation#transmissions-lines) -- 
"Each individual [transmission] line represents a parent-child branch in the phylogenetic tree where the value of the current geographic resolution differs. This means that if values for the geographic resolution haven’t been inferred for internal nodes of the tree then no transmission lines can be drawn". 

Assuming that admin divisions and locations are showing up on the map as demes (circles) and that you're wishing to view transmission lines between them, you'll need infer values for admin divisions and locations  across the internal nodes of the tree. This is the step in the build pipeline using `augur traits`. 

Note that `augur traits` runs a DTA model and the validity of inferring values for geo-resolutions such as this, which often have large sampling biases, must be considered. This is why we do not infer such transmissions for the main nextstrain builds.

**Comment by emmahodcroft** [comment]
Hi @marqsbla - yes this is calculated during the build, and if you want lines for more states, you'll need to modify the build so that `augur traits` runs for the geographic resolution you want to see (`location` `division` etc). 

I don't know how you're running your build, but if you're using the profiles, you can set what geo-resolution to run by modifying your `builds.yaml` file for that 'build'. There's a good example in the `my_profiles/example_advanced_customization/builds.yaml` on [line 155-161](https://github.com/nextstrain/ncov/blob/master/my_profiles/example_advanced_customization/builds.yaml#L155). Hopefully you can use this to template for your own build!

**Comment by marqsbla** [comment]
great, thanks for quick answer. I'm building via profiles, but didn't see how I can influence the build. Thanks for pointing me what should be done. @jameshadfield  I've read this documentation before but didn't found any solution there, thanks. I will try to rebuild look into the pointed places and come back here. 
Thanks again

**Comment by marqsbla** [comment]
It definately helped, thanks :). But I have problems understanding small technicalities and still didn't solve all the issues.
My traits config:

_traits:
  mycountry:
    sampling_bias_correction: 2.5
    columns: ["division_exposure", "country_exposure"]
  mydivision:
    sampling_bias_correction: 2.5
    columns: ["division_exposure", "location"]

exposure:
  mycountry:
    trait: "division"
    exposure: "division_exposure"
  mydivision:
    trait: "division"
    exposure: "division_exposure"_

for "mycountry" I have transmission lines for geographic resolution equal to division but not for countries. When I've changed:
_exposure:
  mycountry:
    trait: "**country**"
    exposure: "**country_exposure**"_
I got transmission lines for  countries but not for divisions. 

for mydivision, I have transmission lines for divison and location, but not for countries and this is ok. 
My question is, can I provide transmission lines for geographic resolution equal to country and division for "mycountry"? How can I do it? What does "_exposure_" dictionary actually configuring, because I don't understand that part?

**Comment by emmahodcroft** [comment]
Hi @marqsbla ! I'm glad this is at least partially working for you - that's great news!

Yes, unfortunately the exposure part is a bit confusing. What this does it ensures that we can replace the ends of nodes with the 'exposed' place (location, division, country) after the analysis - so that one can look at both. But it's a bit optional. 

The easiest solution might be to just use either `["division", "country_exposure"]` or `["division_exposure", "country"]` with the second part that corresponds to whether you're using `country_exposure` or `division_exposure` - hopefully that makes sense! 

This does mean that you won't the 'exposure' locations for whichever one you use, but I'm not sure our script supports replacing both of these. You could try using a list to do so... but I'm not sure if it would work! 

(ex:
```
exposure:
    mycountry:
        trait: ["division", "country"]
        exposure: ["division_exposure", "country_exposure"]
```
 But again - not sure our code will accept this!)

**Comment by marqsbla** [comment]
Hi @emmahodcroft, thanks, but none of the options worked for me. 

["division", "country_exposure"] or ["division_exposure", "country"] behave... strange. For instance lines from my country to its divisions... ;) The lines are still drawn either for country or divisions, not both.

Making list in trait and exposure result in build error (list not supported in ./scripts/modify-tree-according-to-exposure.py). 

Do you have any other ideas? :)

**Comment by emmahodcroft** [comment]
Hi @marqsbla Sorry about the delay. Can you try running just with `["country", "division"]` - and then you can leave the `exposure` block for 'my_country' out completely. See if this works? We think you probably can't do exposure for two traits (our script just doesn't support) but you should in theory be able to do transmission lines for two traits. Let us know how this turns out!

**Comment by marqsbla** [comment]
Hi, thanks.

It doesn't work for me neither. I tried: 
`traits:
  mycountry:
    sampling_bias_correction: 2.5
    columns: ["division", "country"]`
without exposure and I have some error during execution:
`
job 6: Adjusting main auspice JSON to take into account travel history


        /usr/bin/python3.6 ./scripts/modify-tree-according-to-exposure.py             --input results/mycountry/ncov_with_accessions.json             --colors nextstrain_profiles/mycountry-from-swiss/colors.tsv             --lat-longs defaults/lat_longs.tsv             --sampling country             --exposure country_exposure             --output results/mycountry/ncov_with_accessions_and_travel_branches.json 2>&1 | tee logs/incorporate_travel_history_mycountry.txt
        
Traceback (most recent call last):
  File "./scripts/modify-tree-according-to-exposure.py", line 141, in <module>
    traverse(input_json["tree"], switch_attribute)
  File "./scripts/modify-tree-according-to-exposure.py", line 8, in traverse
    fun(node)
  File "./scripts/modify-tree-according-to-exposure.py", line 64, in switch_attribute
    raise Exception("Where there's SAMPLING_TRAIT we should always have EXPOSURE_TRAIT")
Exception: Where there's SAMPLING_TRAIT we should always have EXPOSURE_TRAIT
[Wed Jul 22 15:33:41 2020]
Error in rule incorporate_travel_history:
    jobid: 6
    output: results/mycountry/ncov_with_accessions_and_travel_branches.json
    log: logs/incorporate_travel_history_mycountry.txt (check log file(s) for error message)
    shell:
        
        /usr/bin/python3.6 ./scripts/modify-tree-according-to-exposure.py             --input results/mycountry/ncov_with_accessions.json             --colors nextstrain_profiles/mycountry-from-swiss/colors.tsv             --lat-longs defaults/lat_longs.tsv             --sampling country             --exposure country_exposure             --output results/mycountry/ncov_with_accessions_and_travel_branches.json 2>&1 | tee logs/incorporate_travel_history_mycountry.txt
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Job failed, going on with independent jobs.
Exiting because a job execution failed. Look above for error message
`
I'm thinking whether it is taking exposure settings from default profile? Should I comment it there? or maybe make the exposure void? 

I tried also such config without exposure:
`traits:
  mycountry:
    sampling_bias_correction: 2.5
    columns: ["division_exposure", "country_exposure"]`
but the results are the same. Transmission lines only for countries.

**Comment by trvrb** [comment]
Hi @marqsbla, I hope you were able to resolve this issue. Please let us know if you're continuing to run into this problem.

I would note here that "exposure" location is definitely complicating things. I don't know if there's some way that this could be streamlined for the future.

**Comment by marqsbla** [comment]
Hi, I made different builds. It is not exactly what I wanted, but it suites my needs. 
Thanks, Marek
