### ISSUE TITLE
build tree failed and slow

### ISSUE THREAD

**Issue by xkxxfyf** [nextstrain/ncov#481]
hi, i try to build tree with gisaid`s fasta data without subsample, There are 60,000 sequences , and the ahead steps is right until build tree ,there is error info:
![image](https://user-images.githubusercontent.com/25799295/89897983-80675880-dc12-11ea-9cea-d32977523a4f.png)

by the way, the step of building tree is so slow and i already use parameter "set-threads: tree=24" , But I saw that the program still uses only one CPU . why?
the version of nextstrain.cli is 2.0.0.post1, augur 9.0.0

**Comment by sashitt2** [comment]
how did you run it without subsampling?

**Comment by trvrb** [comment]
Running IQ-TREE with 60,000 genomes is going to be necessarily slow. In the above screenshot it looks like an issue within IQ-TREE based on `bad_alloc` call. I'm going to close this issue now, but please @xkxxfyf re-open if you have a further question here. Best of luck with getting things running on the bigger sample sets. You might also want to try using `--method fasttree` instead of IQ-TREE or upgrade to IQ-TREE v2 that is designed for SARS-CoV-2 trees.
