### ISSUE TITLE
Issue in Clade Assignment

### ISSUE THREAD

**Issue by ps120195** [nextstrain/ncov#493]
I am getting wrong tree after Clade assignment. 
  
The data supposed to be present in A2a clade is coming in A2. I tried rerunning the all steps by checking all input files, Still I am not getting expected results.  

Can there be any solution regarding this.

**Comment by emmahodcroft** [comment]
Hi @ps120195 , thanks for reaching out! I'm sorry you're having trouble. The clades you are referring to are some of our 'legacy clades' - the temporary clade system we set up early in the pandemic, but which was never intended to be permanent. We no longer support these clades - we now recommend using the 'Nextstrain Clades' which you can see on the main Nextstrain builds: https://nextstrain.org/ncov/global?c=clade_membership

If you don't want to change anything else in the repository (it has probably changed quite a bit since you downloaded it), you can get a copy of the current clades file here: https://github.com/nextstrain/ncov/blob/master/defaults/clades.tsv

If you replace the current clades file with this one in your own repository currently, you'll switch to using the current Nextstrain clades. I hope that helps!

**Comment by ps120195** [comment]
Thank you for your kind response. Actually I faced this issue earlier also, but after few repeatitions I was able to get correct tree based on that defined  clades. But this is the first time I m struggling with wrong output since 4 days. I thought it is due to alignment issue. But after several runs, still this issue is not resolved. I really want to use my defined clade file. Can you please help me out. If you want to test run , I am happy to share my clades.tsv file which I am using.

**Comment by emmahodcroft** [comment]
Hi @ps120195 . I'm afraid it's going to be difficult to debug this as we no longer support the older version of the clades file. A2 and A2a only differ by one mutation, as far as I can tell - so a simple swap of where these mutations are predicted to have arisen on the tree may lead to these clades getting mixed up. This is one of the reasons we've moved to the new clade system - it's much more robust.

How are you determining that the sequences 'should' be in A2a? These should be sequences that have an AA mutation to L in ORF1b position 314. Currently, there aren't a large number of sequences in our tree which have this mutation.

**Comment by trvrb** [comment]
I hope you were able to resolve this @ps120195. I'm going to close this issue. The "old" clades file with A2, A2a, etc... is no longer supported and newer datasets won't necessarily work correctly. I'd recommend using current clades (https://nextstrain.org/blog/2021-01-06-updated-SARS-CoV-2-clade-naming) which are continually updated and tested against new data.
