### ISSUE TITLE
Help needed for builds.yaml

### ISSUE THREAD

**Issue by nahid18** [nextstrain/ncov#497]
Hi,
The ncov pipeline is working perfectly fine. However, I am having some trouble to configure the `builds.yaml` file.
Here's my current `builds.yaml` file looks like:

```sh
builds:
  bangladesh:
    subsampling_scheme: bangladesh
    region: Asia
    country: Bangladesh
    title: "SARS-CoV-2 Sequences in Bangladesh"

subsampling:
  bangladesh:

    country:
      group_by: "division year month"
      seq_per_group: 302
      exclude: "--exclude-where 'country!={country}'"

    region:
      group_by: "country year month"
      seq_per_group: 50
      exclude: "--exclude-where 'country={country}'"
      priorities:
        type: "proximity"
        focus: "country"
```

I have skipped the files configuration part here. This configuration works as intended. 

Here's the `country` legends from `auspice.us`:

![country](https://user-images.githubusercontent.com/43277262/95100388-dc51e780-0752-11eb-867e-72b9ae142c12.png)

As you can see, the target country and it's regional countries are showing correctly. However, the countries from different regions have become one group, which is a problem. I want to show those countries separately just like the other countries shown in here. I also don't want to show the `Asia` region legend here.

How can I change something to make sure the countries from other regions don't group together and show separately and also to not show the legend `Asia` region here since it has no grouped sample (rather individual countries) in the generated output file?

Thank you.

**Comment by nahid18** [comment]
Hi, can anyone help me? 
@emmahodcroft

**Comment by jameshadfield** [comment]
The grouping of countries into regions (e.g. "Europe"), as shown in the legend above, is happening thanks to [this rule](https://github.com/nextstrain/ncov/blob/master/workflow/snakemake_rules/main_workflow.smk#L461-L481) in the pipeline which runs [this script](https://github.com/nextstrain/ncov/blob/master/scripts/adjust_regional_meta.py).

After looking at the script invocation, I believe you can avoid it's effects by simply removing the `region: Asia` entry from  `builds -> bangladesh` in your `builds.yaml`. This may have unintended consequences elsewhere, although it doesn't look like your subsampling scheme relies on `region`.  Tagging @huddlej (as well as Emma) who may know a better solution here.

**Comment by nahid18** [comment]
Removing the Asia `region` from the build configuration worked as intended. Thanks a lot! 
However, `Iran` was added to the legend for no reason. Why is that and how can I remove that?

**Comment by emmahodcroft** [comment]
Hi @nahid18 , sorry for the delay with your request! My best suggestion is also that given by James. We collapse these other regions outside of the focal region to make the display easier when doing these kinds of focal runs, but it's true that this may not always be wanted!

Another thing I believe the above rule/script does is it removes colorings from areas where they are just an 'exposure' - for example, we know they had travel history to that place, but the sequence was taken somewhere else. It's likely that some of your sequences have an 'exposure' in Iran, so that's why it's showing up in the legend. I'm afraid I don't know of a simple way to correct this - you possibly might have to modify your own version of the above script which just takes out exposures without modifying regions! Or, just have Iran hanging out in the legend :)

**Comment by nahid18** [comment]
Thank you everyone!
