### ISSUE TITLE
Please add `CAL.20C` branch (Variant from Southern California) to nextstrain

### ISSUE THREAD

**Issue by ayumi-cloud** [nextstrain/ncov#570]
Please add `CAL.20C` branch to nextstrain

Here a screenshot:

![image](https://user-images.githubusercontent.com/57409060/109727172-c3d3e500-7bab-11eb-8178-37d546ae0b0c.png)

Going to link to the paper: [Emergence of a Novel SARS-CoV-2 Variant in Southern California](https://jamanetwork.com/journals/jama/fullarticle/2776543)

I did some searching on Nextstrain and CoVariants couldn't find any info on this interesting branch.

Worth saying it contains the `L452R` mutation which was markedly resistant to some mAbs - see an old paper found here: https://www.cell.com/cell/fulltext/S0092-8674(20)30877-1

Also the Nextrain is giving an incorrect result for USA:

![image](https://user-images.githubusercontent.com/57409060/109727365-23ca8b80-7bac-11eb-99b2-7dbebd32d205.png)

It's saying `20G` is 55%, but reading the papers they are saying there are more cases of `CAL.20C` than `20G`.

**Comment by emmahodcroft** [comment]
Hi @ayumi-cloud  - thanks for reaching out! The variant called CAL.20C in the Nextstrain naming scheme would be called 20C/S:452R. But it's true that the proliferation of names makes this confusing!

You can find 20C/S:452R on CoVariants under the label 'S:L452R' - [see here](https://covariants.org/variants/S.L452R). I'm updating these names very soon so that they'll correctly reflect the Nextstrain naming scheme!

At Nextstrain we only give clades labels when they meet certain criteria - you can read more about this [here](https://nextstrain.org/blog/2021-01-06-updated-SARS-CoV-2-clade-naming).

So for example, this cluster would need to be at 30% frequency or more in North America for 2 or more months to get a label on the main Nextstrain site - or be designated a Variant of Concern.  At the moment, this variant is about 12% in our North American Build, so would not qualify yet ([link](https://nextstrain.org/ncov/north-america?c=gt-S_452&f_region=North%20America&p=grid)):
![image](https://user-images.githubusercontent.com/14290674/109848822-fedc2400-7c50-11eb-9b1e-3a8197234519.png)

On a North American scale, this is not more than 20G, which is over 40% of sequences. However, perhaps the papers are referring to the relative levels of sequences seen in a particular area - in which case it's possible they may be seeing more 20C/S:452R than 20G.

I hope that helps!

**Comment by ayumi-cloud** [comment]
Thank you, your comment helps a lot!
