### ISSUE TITLE
Nextstrain issue

### ISSUE THREAD

**Issue by Leatherneck1** [nextstrain/ncov#584]
**Current Behavior**
When using the online Nextstrain, none of the B.1.1.7 or P.1 strains (18 all told) show up when sorting either the Global or North America databases, and using Oregon as the filtering division.  Also a search by specific ID (example USA/OR-OHSU-PHL00043/2021) does not show it in the database any longer. They used to mid February, not sure what changes broke the code.

**Expected behavior**
For Oregon strains to show up on the "more aggressive" variants.

**How to reproduce**
Steps to reproduce the current behavior:
Visit https://nextstrain.org/ncov/north-america?dmin=2021-01-21&f_division=Oregon&l=radial&tl=author
4. See no results showing for B1.1.7 or P.1.  Others show, like the B1.1429/1427 aka "Cali" variants.

**Possible solution**
I wish I knew

**Your environment: if browsing Nextstrain online**
 - Operating system: Windows
 - Browser: Happens with both Chrome and Edge

**Additional context**
Sample from Feb back when Oregon Division used to work:
![Nextstrain from Feb](https://user-images.githubusercontent.com/80787671/111373386-0fc96400-8659-11eb-95a1-69c58cfc8fb3.jpg)

**Comment by jameshadfield** [comment]
This is due to stochastic subsampling we use to reduce the entire GISAID dataset (700k genomes last time I checked) down to a manageable number of genomes for visualisation. Each time we rerun the analysis the samples genomes will change.

There are now quite a few different analyses available on nextstrain (see https://nextstrain.org/sars-cov-2/ for a list). This [SPHERES managed analysis focuses on Oregon](https://nextstrain.org/groups/spheres/ncov/oregon) and includes `USA/OR-OHSU-PHL00043/2021`.
