### ISSUE TITLE
Speed up workflow by using subsampled metadata 

### ISSUE THREAD

**Issue by trvrb** [nextstrain/ncov#654]
Right now rules like `colors` will result in a call that looks like:

```
python3 scripts/assign-colors.py
  --ordering defaults/color_ordering.tsv
  --color-schemes defaults/color_schemes.tsv
  --output results/global/colors.tsv
  --metadata results/sanitized_metadata_gisaid.tsv.xz
```

where the entire ~1.7M line metadata file is passed into the script. This causes this rule to take 8 minutes when running locally. However, this rule could be called just as well as:

```
python3 scripts/assign-colors.py
  --ordering defaults/color_ordering.tsv
  --color-schemes defaults/color_schemes.tsv
  --output results/global/colors.tsv
  --metadata results/global/global_subsampled_metadata.tsv.xz
```

where just the ~4k line metadata file is passed in. This runs in 1.6 seconds (!) instead.

We have the same story with the `export` rule that currently is called as:

```
augur export v2
 --metadata results/sanitized_metadata_gisaid.tsv.xz
...
```

and takes 55 seconds. It could instead be called as:

```
augur export v2
 --metadata results/global/global_subsampled_metadata.tsv.xz
...
```

and take 9 seconds.

Similarly, correcting the `recency` rule goes from 66 seconds to <1 second.

The issue is that `_get_metadata_by_wildcards` is not actually returning the build-specific subsampled metadata. Instead it's defaulting to the broader `results/sanitized_metadata_gisaid.tsv.xz`. 

Besides `colors` and `export` there are a number of rules that rely on metadata. I'm assuming that correcting the input will speed these up as well. But even just fixing `colors`, `recency` and `export` would save ~60 minutes (!) of single-core compute in the daily rebuilds.

I'm not immediately sure how to correct this. @huddlej, would you be able to take a look? I'm assuming this bit of the workflow is something you're quite familiar with.

**Comment by emmahodcroft** [comment]
Amazing catch Trevor!

**Comment by huddlej** [comment]
Wow, this is definitely a bug. There are several places that we should update to use the subsampled metadata instead of the full metadata including these:

 - https://github.com/nextstrain/ncov/blob/c1a1e3e5d3396df9780a2d1b64cb5181977349e3/workflow/snakemake_rules/main_workflow.smk#L640
 - https://github.com/nextstrain/ncov/blob/c1a1e3e5d3396df9780a2d1b64cb5181977349e3/workflow/snakemake_rules/main_workflow.smk#L697
 - https://github.com/nextstrain/ncov/blob/c1a1e3e5d3396df9780a2d1b64cb5181977349e3/workflow/snakemake_rules/main_workflow.smk#L891
 - https://github.com/nextstrain/ncov/blob/c1a1e3e5d3396df9780a2d1b64cb5181977349e3/workflow/snakemake_rules/main_workflow.smk#L1009
 - https://github.com/nextstrain/ncov/blob/c1a1e3e5d3396df9780a2d1b64cb5181977349e3/workflow/snakemake_rules/main_workflow.smk#L1034
 - https://github.com/nextstrain/ncov/blob/c1a1e3e5d3396df9780a2d1b64cb5181977349e3/workflow/snakemake_rules/main_workflow.smk#L1056
 - https://github.com/nextstrain/ncov/blob/c1a1e3e5d3396df9780a2d1b64cb5181977349e3/workflow/snakemake_rules/main_workflow.smk#L1173
 - https://github.com/nextstrain/ncov/blob/c1a1e3e5d3396df9780a2d1b64cb5181977349e3/workflow/snakemake_rules/export_for_nextstrain.smk#L68
