### ISSUE TITLE
/fetch/ not happy with numeric IP address?

### ISSUE THREAD

**Issue by AngieHinrichs** [nextstrain/ncov#883]
**Current Behavior**
This link with "/fetch/128.114.119.131/..." (numeric IP address) does not work:

https://nextstrain.org/fetch/128.114.119.131/trash/ct/subtreeAuspice1_128_4107f_6b2240.json

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/186983/157327938-254b9e08-16ea-4602-b51f-0a8b83730528.png">

However, if I replace "128.114.119.131" with "genome.ucsc.edu", it does work:

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_128_4107f_6b2240.json

<img width="641" alt="image" src="https://user-images.githubusercontent.com/186983/157328081-5ac26133-eb21-4c63-b758-6dacf80403ca.png">

This was [reported on Twitter](https://twitter.com/lixingguang/status/1501154590141472771).  I believe the numeric IP address was used because of firewall issues in China with genome.ucsc.edu.  (At least nextstrain.org gets through!)

**Expected behavior**
It would be nice for /fetch/ to support numeric IP addresses.  Hopefully just a little regex tweak?  :)

Thanks!

**Comment by jameshadfield** [comment]
I think this is due to the fact that the SSL certificate is tied to the domain name, not the IP. [Nextstrain fetch enforces https](https://docs.nextstrain.org/en/latest/guides/share/fetch-via-urls.html#notes) and we can see that loading https://128.114.119.132/trash/ct/subtreeAuspice1_128_4107f_6b2240.json [1] in a browser (Firefox 97.0.1 in my case) doesn’t work. 

![image](https://user-images.githubusercontent.com/8350992/157595894-44057339-765f-4d50-912c-34a2da201839.png)


Curl commands indicate the same:

```bash
# this works:
$ curl https://genome.ucsc.edu/trash/ct/subtreeAuspice1_128_4107f_6b2240.json -o data.json
# this doesn't:
$ curl https://128.114.119.132/trash/ct/subtreeAuspice1_128_4107f_6b2240.json -o data.json
curl: (60) SSL: no alternative certificate subject name matches target host name '128.114.119.132'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

# Note that this does (http:// not https://)
$ curl http://128.114.119.132/trash/ct/subtreeAuspice1_128_4107f_6b2240.json -o data.json
# and so does this
$ curl 128.114.119.132/trash/ct/subtreeAuspice1_128_4107f_6b2240.json -o data.json
```

---

I've wanted to support different protocols for /fetch/ but it's slightly complicated by some URI limitations, and I think https is working for most use cases.

[1] I'm using 128.114.119.132 as according to `curl --head https://genome.ucsc.edu/trash/ct/subtreeAuspice1_128_4107f_6b2240.json -verbose` the IP address is 128.114.119.132.  It has the same behaviour as `128.114.119.131`.
